artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/tsohail12/Datasets/raw/refs/heads/main/archive%20(10).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/bmw.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/bmw.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.pkl
  metric_file_name: artifacts/model_evaluation/metrics.json